<%@ Page Language="C#" ContentType="text/plain" AutoEventWireup="true" CodeBehind="CodeTemplate.aspx.cs" Inherits="SitecoreORM.CodeTemplate" %>
// SitecoreORM. Open Source Code Generator for Sitecore
// Autogenerated code: <%# DateTime.Now.ToShortDateString() %> <%# DateTime.Now.ToShortTimeString() %>
using System;
using Sitecore;
using Sitecore.Data.Items;
using Sitecore.Diagnostics;  
using Sitecore.Collections;

namespace <%# Namespace %>
{
  /// <summary>
  /// Code representation of item based on Sitecore template <%# Template.InnerItem.Paths.FullPath %>
  /// </summary>
  public class <%# ClassName %> : BaseItem
  {
   
    /// <summary>
    /// Creates an instance of a Sitecore item based on Sitecore template <%# Template.InnerItem.Paths.FullPath %>
    /// </summary>
    /// <param name="innerItem">Sitecore item</param>
    public <%# ClassName %>(Item innerItem)
    {
      InnerItem = innerItem;
    } 
    
    /// <summary>
    /// Validates that the given item is based on the Sitecore template <%# Template.InnerItem.Paths.FullPath %>
    /// </summary>
    /// <param name="item">Sitecore item</param>
    /// <returns>True if item is based on the same Sitecore template</returns>
    public static bool IsValid(Item item)
    {
      return item.TemplateID == new ID("<%# Template.ID %>");  
    }

    public Item InnerItem { get; private set; }

    public override FieldCollection Fields
    {
      get { return InnerItem.Fields; }
    }
    
    #region Inherited Templates    
<%# ExecuteCodeProvider("SitecoreORM.CodeProviders.GenerateInheritedTemplateProperties, SitecoreORM", "/sitecore modules/shell/sitecoreorm/inheritedtemplatetemplates/inheritedtemplate.aspx") %>
    #endregion

    #region Fields    
<%# ExecuteCodeProvider("SitecoreORM.CodeProviders.GenerateFieldProperties, SitecoreORM", "/sitecore modules/shell/sitecoreorm/fieldtemplates/") %>
    #endregion

    #region field names
    public struct FieldNames
    {  
<%# ExecuteCodeProvider("SitecoreORM.CodeProviders.GenerateFieldNames, SitecoreORM") %>
    }   
    #endregion
  }
}
